name: Auto Redeploy

# Wyzwalacze workflow
on:
  schedule:
    - cron: "0 0 * * *"  # codziennie o północy czasu polskiego
  workflow_dispatch:  # możliwość ręcznego uruchomienia

# Ustawienie strefy czasowej
env:
  TZ: Europe/Warsaw

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_NO_EXP_FULL_TOKEN  }}

      - name: Create fake commit
        run: |
          echo "Redeploy triggered at $(date)" >> redeploy.txt
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add redeploy.txt
          git commit -m "Auto redeploy trigger [skip ci]" || echo "No changes to commit"

      - name: Set remote with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.PAT_NO_EXP_FULL_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Push changes
        run: git push
